name: Test & Build Docker Image
on:
  workflow_dispatch
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: .
            key: {{ $github.sha }}
        - name: Debug
          run: |
            cd $GITHUB_WORKSPACE && pwd && ls -las
            cd $GITHUB_WORKSPACE/deploy && pwd && ls -las
            cd $GITHUB_WORKSPACE/.. && pwd && ls -las
        - uses: actions/setup-go@v3
          with:
            go-version: '1.18.0'
        - name: Test Application
          run: |
            go build -v ./... && go test -v ./...
  build:
    name: Build Docker Image
    uses: Pinoga/tradingbuild/.github/workflows/build-image.yml@main
    needs: test
    with:
      PROJECT: chat
      SCOPE: services
      BUILD_VERSION: 0.0.1
      BUILD_BRANCH: main

          

